sudo: true

install:
  - curl -sLo - http://j.mp/install-travis-docker | sh -xe

script:
  - ./run "docker version"
  - ./run "docker build -t drupal . && docker run --name drupal -e BUILD_TEST=1 -i drupal"
