sudo: required

services:
  - docker

env:
  global:
    - APP_IMAGE_NAME=zaporylie/drupal
    - APP_CONTAINER_NAME=drupal
    - DB_CONTAINER_NAME=mysql
    - DB_VERSION=5.5
  matrix:
    - DB_HOSTNAME=
    - DB_HOSTNAME=mysql
    - DB_HOSTNAME=mysql DB_VERSION=5.6

script:
  # Show version of Docker used to build image and run container.
  - docker version
  # Build image (use the same namespace as on docker hub)
  - docker build -t ${APP_IMAGE_NAME} .
  # Run mysql container.
  - docker run -d --name ${DB_CONTAINER_NAME} -e MYSQL_ROOT_PASSWORD=test mysql:${DB_VERSION}
  # Show all docker images.
  - docker images
  # Show all container.
  - docker ps -a
  # Run container in test mode.
  - docker run -i --name ${APP_CONTAINER_NAME} --link ${DB_CONTAINER_NAME}:${DB_HOSTNAME} -e DB_HOSTNAME=${DB_HOSTNAME} -e BUILD_TEST=1 ${APP_IMAGE_NAME}
