sudo: true

env:
  global:
    - DOCKER_VERSION=1.7.1  # Install Docker version 1.7.1
    - DOCKER_VERSION=get.docker.com  # Install Docker using get.docker.com (may break)

    - BRANCH=stable         # Use 'stable' branch

    - QUIET=1               # Less verbose logging
    - UML_FIG=0             # Don't install fig
    - UML_DOCKERCOMPOSE=1   # Install docker-compose

install:
  - curl -sLo - http://j.mp/install-travis-docker | sh -xe

script:
  - ./run docker version
  - ./run docker build -t zaporylie/drupal .
  - ./run docker run --name mysql_service -e MYSQL_ROOT_PASSWORD=test -d mysql:5.5
  - ./run docker run --name drupal --link mysql_service:mysql -e BUILD_TEST=1 -ti -p 80:80 zaporylie/drupal
